In [128]:
import pandas as pd
from src import pipelines as P
from pathlib import Path
import re
import numpy as np
import torch

In [4]:
nomen = P.get_nomen()

In [5]:
nomen

                   Nomen Artikel
1                    Ich       n
4                    Ist       n
9                     Es       n
11                   Was       m
20                   Wie       n
...                  ...     ...
308571     Teppichmesser       n
308574       Holzspalter       m
308577  Obergesellschaft       f
308582       Brandstelle       f
308591        Bissigkeit       f

[33631 rows x 2 columns]

In [6]:
n2 = pd.read_csv('nouns.csv')

/tmp/ipykernel_48153/3213972919.py:1: DtypeWarning: Columns (0: genus 3, 1: genus 4, 2: nominativ singular*, 3: nominativ singular 3, 4: nominativ singular 4, 5: nominativ plural 3, 6: nominativ plural 4, 7: genitiv singular 3, 8: genitiv singular 4, 9: genitiv plural 3, 10: genitiv plural 4, 11: dativ singular 3, 12: dativ singular 4, 13: dativ plural 3, 14: dativ plural 4, 15: akkusativ singular 3, 16: akkusativ singular 4, 17: akkusativ plural 3, 18: akkusativ plural 4) have mixed types. Specify dtype option on import or set low_memory=False.
  n2 = pd.read_csv('nouns.csv')

In [7]:
n2

,lemma,pos,genus,genus 1,genus 2,genus 3,genus 4,nominativ singular,nominativ singular*,nominativ singular 1,...,akkusativ singular gemischt,akkusativ plural,akkusativ plural*,akkusativ plural 1,akkusativ plural 2,akkusativ plural 3,akkusativ plural 4,akkusativ plural stark,akkusativ plural schwach,akkusativ plural gemischt
0,-algie,"Gebundenes Lexem,Substantiv",f,NaN,NaN,NaN,NaN,-algie,NaN,NaN,...,NaN,-algien,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-ant,"Affix,Substantiv,Suffix",NaN,m,n,NaN,NaN,NaN,NaN,-ant,...,NaN,NaN,NaN,-anten,-ante,NaN,NaN,NaN,NaN,NaN
2,-anz,"Affix,Substantiv,Suffix",f,NaN,NaN,NaN,NaN,-anz,NaN,NaN,...,NaN,-anzen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-chen,"Affix,Substantiv,Suffix",n,NaN,NaN,NaN,NaN,-chen,NaN,NaN,...,NaN,-chen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-elchen,"Affix,Substantiv,Suffix",n,NaN,NaN,NaN,NaN,-elchen,NaN,NaN,...,NaN,-elchen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102439,Ḫāriǧit,Substantiv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102440,’Ndrangheta,Substantiv,f,NaN,NaN,NaN,NaN,’Ndrangheta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102441,’Sgebengu,Substantiv,m,NaN,NaN,NaN,NaN,’Sgebengu,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102442,’s-Gravenhage,"Substantiv,Toponym",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102443,’s-Hertogenbosch,"Substantiv,Toponym",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
def line_read(data): #any word that has number in it is not included
    article = {}
    with open(data, "r", encoding="utf-8") as file: 
        content = file.read()
        ct = 0
        for line in re.split(r"[\n;]", content):
            line = line.strip()
            words = line.split()
            if(len(words)>1 and len(words[1]) > 2):
                if(words[1][0] == '{' and words[1][2] == '}'):
                    print(words[0])
                    has_number = any(char.isdigit() for char in words[0])
                    if not has_number:
                        article[words[0]] = words[1][1]
                    
                    ct+=1
                    
    return article

In [99]:
art = line_read('raw_data/de-en.txt')

A
Ais
As
Aisis
Ases
Aal
Aachener
Aachenerin
Aalbestand
Aalspieß
Aalen
Aalenium
Aalfang
Aalfischerei
Aalhaut
Aalleiter
Aaltreppe
Aalpass
Aalräucherei
Aalreuse
Aalstrich
Aalstrich
Aalsuppe
Aalterrine
Aas
Aasfleisch
Aas
Aaronsstab
Aasfliege
Aasfresser
Aasgeier
Aasjäger
Aaskäfer
Aaskrähe
Abacá
Abaka
Manilahanf
Abachi
Abakusblume
Abakussäule
A-Batterie
A-Betrieb
Abazissus
Abänderung
Modifikation
Modifizierung
Abänderungsantrag
Ergänzungsantrag
Zusatzantrag
Änderungsantrag
Abänderungsbefugnis
Abänderungsklage
Abänderungsurkunde
Abänderungsvorschlag
Ergänzungsvorschlag
Abandon
Abandonerklärung
Abandonerklärung
Abandonfrist
Abandonist
Abandonrevers
Abarbeitung
Abarbeiten
Abarbeitungsfolge
Abarbeitungszeit
Bearbeitungszeit
Bearbeitungsdauer
Abarbeitungszyklus
Abart
Variante
Variation
Abartigkeit
Abbau
Zersetzung
Degradierung
Abbau
Abbau
Abbau
Ausbeuten
Abbau
Abbauen
Demontage
Zerlegen
Abbau
Rückbau
Abbau
Gewinnung
Förderung
Ausbeutung
Abbau
Tagebau
Abraumbau
Abbau
Dämpfung
Abbaubarkeit
Abbaublock
Abbauerlaubnis
Abbaugenehmigung
Abbaufeld
Abbaufrist
Abbaugebiet
Abbaugenehmigungsantrag
Abbaugeschwindigkeit
Abbaurate
Abbaugrad
Abbauhammer
Pickhammer
Abbauhöhe
Vorgriff
Abbauintoxikation
Abbauland
Abbauleistung
Abbaumaschine
Abbauphase
Abbaustadium
Abbauprodukt
Abbauprodukt
Abbaureaktion
Abbaurevier
Abbaurichtung
Abbauriss
Abbaustoffwechsel
Katabolismus
Dissimilation
Abbauscheibe
Abbauschutt
Abbaustelle
Abbaustoß
Stoß
Abbaustrecke
Abbaustufe
Abbauschritt
Abbauverfahren
Abbauvertrag
Abbaukontrakt
Abbauvorgang
Abbauprozess
Abbauwand
Abbauwert
Abbauwürdigkeit
Abbauzeit
Abbe
Abbé
Abbeermaschine
Entstielmaschine
Abbeilen
Abbeizen
Abbeizpaste
Abbe-Zahl
Abbestellung
Abbiegen
Abbieger
Abbiegescheinwerfer
Abbiegespur
Abbiegestreifen
Abbiegeunfall
Abbiegeverbot
Abbiegeverhalten
Abbiegeverkehr
Abbiegestelle
Abbild
Abbildung
Zuordnung
Ordnungshomomorphismus
Abbildungsbreite
Klangkörperausdehnung
Abbildungsfehler
Abbildtheorie
Abbildungsgenauigkeit
Abbildungsqualität
Abbildungsgleichung
Abbildungslegende
Bildlegende
Legende
Bildzeile
Bildüberschrift
Bildunterschrift
Abbildungsmaßstab
Abbildungsoptik
Abbildungsoptik
Abbildungsregister
Abbildungsverzeichnis
Abbindebeginn
Abbindebereich
Abbindeende
Abbindebehandlung
Abbindebeschleuniger
Abbindebeschleunigung
Abbindedauer
Abbindeenergie
Abbinden
Unterbinden
Unterbindung
Ligatur
Abbinden
Abbindeplatz
Abbindelager
Abbindeprozess
Abbindevorgang
Abbindeverlauf
Abbindeprüfung
Abbindereaktion
Abbinderegulator
Abbindeschwindung
Abbindeschwund
Abbindesteuerung
Abbindestörung
Abbindetemperatur
Abbindetest
Abbindeprüfung
Abbindeverhalten
Abbindeverzögerer
Abbindewasser
Abbindewärme
Hydratationswärme
Abbindewärme
Abbindezeit
Abbindezeit
Abbindungsfaden
Unterbindungsfaden
Ligaturfaden
Abbitte
Abblaseabsperrventil
Abblasebehälter
Abblasetank
Abblasebehälterkühler
Abblasedampf
Abblasedruck
Abblasedruckregler
Abblaseeinrichtung
Abblaseeinrichtung
Abblasegrenzdruckregler
Abblasehaube
Abblaseleistung
Abblaseleitung
Abblasemast
Abblasemenge
Abblaseregelung
Abblaseregelventil
Abblaserohr
Ausblaserohr
Durchblaserohr
Abblaseschalldämpfer
Abblaseschieber
Abblaseventil
Abblaseschnellschlussventil
Abblaseschnellschlußventil
Abblaseschubventil
Abblasestation
Abblasesteuerung
Abblasetauchspulregler
Abblaseventil
Umluftventil
Abblaseverhältnisdruckregler
Abblasevorrichtung
Abblättern
Abplatzen
Abschiefern
Abschieferung
Abschilfern
Abschuppung
Abblättern
Abblätterung
Abblättern
Absplitterung
Absplittern
Abblende
Ausblende
Abblenden
Abblenden
Abblendlicht
Abblendrelais
Abblendschalter
Abblendung
Abbolzung
Abbrand
Abbrand
Abbrand
Atomabbrand
Abbrandberechnung
Abbrechen
Aufbrechen
Aufbruch
Abbrechen
Abbrecher
Abbrecherin
Abbrechung
Abbremsplatz
Abbrechversuch
Abbremsstelle
Abbremsung
Verzögerung
Abbremsvorgang
Abbremszeit
Abbremszeit
Abbrenneinrichtung
Abbrennen
Abbrennrate
Abbrenntemperatur
Abbrennzeit
Abbrennzeit
Abbrennstumpfschweißen
Abbringen
Abhalten
Abbröckeln
Abblättern
Abplatzen
Absplittern
Abbröckelung
Abbruch
Abbrechen
Abbruch
Abriss
Schleifen
Abbruch
Abbruch
Abbruch
Abbruch
Abbruch
Abschneiden
Trunkierung
Abbruch
Abbruchabfall
Abbruchanforderungssignal
Abbruchantrag
Abbrucharbeiter
Abbruchbedingung
Abbruchbagger
Abbruchbeton
Abbruchblutung
Entzugsblutung
Abbruchcode
Abbruchfehler
Abbrechfehler
Abbruchfirma
Abbruchunternehmen
Abbruchgebot
Abbruchanordnung
Abbruchanweisung
Abbruchorder
Abbruchgenehmigung
Abbruchhammer
Abbruchgrundstück
Abbruchhaus
Abbruchholz
Abbruchkante
Bruchkante
Abrisskante
Abbruchkolonne
Sprengkommando
Sprengtrupp
Abbruchkostenschätzung
Abbruchkriterium
Abbruchmakro
Abbruchmaterial
Abbruchmethode
Abbruchphase
Abbruchplan
Abbruchplaner
Abbruchplanung
Abbruchpreis
Abbruchprojekt
Abbruchprozess
Abbruchvorgang
Abbruchreaktion
Abbruchschaufel
Abbruchlöffel
Abbruchschere
Abbruchschutt
Abbruchsimulation
Abbruchspezialist
Abbruchstelle
Abbruchtechniker
Abbruchufer
Abbruchüberwachung
Abbruchverfahren
Abbruchverzögerung
Abbruchaufschub
Abbruchvorbereitung
Abbruchwerkzeug
Abbruchzone
Betrug
Abbuchung
Belastung
Abbuchungsauftrag
Abbuchungszeitraum
ABC-Abwehr
ABC-Profil
Abc-Schütze
I-Dotz
I-Dötzchen
I-Männchen
Taferlklassler
Tafelkratzer
ABC-Spürpanzer
ABC-Terrorismus
Superterrorismus
Abdachung
Schräge
Böschung
Abdampf
Abdampfdruck
Abdampfdurchsatz
Abdampfende
Abdampfenergie
Abdampffeuchte
Abdampfflansch
Abdampfflut
Abdampfgehäuse
Abdampfhaube
Abdampfkrümmer
Abdampfleitung
Abdampfmenge
Abdampfnässe
Abdampfquerschnitt
Abdampfrückstand
Abdampfringraum
Abdampfspeicher
Abdampfstutzen
Abdampfteil
Abdampftemperatur
Abdampfturbine
Abdampfverbindung
Abdampfvolumen
Abdampfvorwärmer
Abdampfverlust
Abdankung
Zurücktreten
Abdankung
Abdeckband
Abdecker
Schinder
Kadaverbeseitiger
Abdeckerei
Abdeckfolie
Abdeckhaube
Abdeckkappe
Kappe
Abdeckklappe
Abdeckklebeband
Abdeckband
Abklebeband
Abklebband
Abdecklack
Abdeckmaterial
Abdeckpapier
Abdeckmutter
Abdeckplane
Abdeckplatte
Abdeckplatte
Abdeckstein
Abdeckplatte
Abdeckprofil
Abdeckrahmen
Abdeckring
Abdeckscheibe
Abdeckschraube
Abdeckstift
Abdeckung
Abdeckung
Abdeckziegel
Abdeckung
Abdeckung
Bedeckung
Verhüllung
Abdeckung
Abdeckung
Freilegung
Rückwand
Abdichten
Abdichtung
Abdichtblech
Abdichtbürste
Abdichten
Abdichten
Bauwerksabdichtung
Abdichten
Abdichtung
Abdichter
Abdichtfarbe
Abdichtgummi
Dichtgummi
Dichtungsgummi
Abdichthülse
Abdichtmasse
Abdichtungsmasse
Abdichtrahmen
Abdichtring
Abdichtstreifen
Dichtungsleiste
Abdichttopf
Abdichtungsband
Abdichtungsfolie
Abdichtungsleiste
Abdichtleiste
Abdichtungsmaterial
Abdichtungsmethode
Abdichtmethode
Abdichtungsverfahren
Abdichtverfahren
Abdichtungspaste
Abdichtungspfropfen
Abdichtungsreserve
Abdichtungssystem
Abdichtungsvorrichtung
Abdichtwand
Abdominallavage
Abdominalsegment
Abdrängungsschreiber
Abdriftschreiber
Abdreheisen
Abdrehen
Abdruck
Abdruck
Guss
Abguss
Abdruck
Eindruck
Gepräge
Abdruck
Prägung
Abdruckmasse
Abdrückdeckel
Abdrückmutter
Abdrückpumpe
Abdrückschraube
Abdrücksignal
Abdrückvorrichtung
Abdunkelungsvorrichtung
Abduktion
Abduktionslähmung
Abduktivismus
Abduktor
Abdunklung
Abdunklungsvorhang
Verdunklungsvorhang
Verdunkelungsvorhang
Abdunklung
Verdunklung
Abelit
Abelson-Tukey-Score-Test
Abend
Abend
Abendandacht
Abendandacht
Abendgottesdienst
Abendanzug
Abendarbeit
Abendausgabe
Abendblatt
Abendbrotzeit
Abendessenzeit
Abenddämmerung
Dämmerung
Dämmer
Abenddämmerung
Niedergang
Ausklang
Abendessen
Abendbrot
Nachtmahl
Nachtessen
Znacht
Gute-Nacht-Imbiss
Abendessen
Abendgebet
Abendgesellschaft
Abendglocke
Abendgottesdienst
Abendhimmel
Abendkarte
Abendkasse
Kasse
Abendkassa
Kassa
Abendkleid
Abendkleid
Abendgarderobe
Abendrobe
Abendkleidung
Abendkurs
Abendland
Okzident
Westen
Abendmahl
Altarssakrament
Eucharistie
Abendlicht
Abendluft
Abendmahlsgottesdienst
Abendmahlswein
Abendmahlzeit
Abendmesse
Abendgottesdienst
Abendmode
Abendpfauenauge
Abendpost
Abendprogramm
Abendrot
Abendröte
Abendröte
Abendschule
Abendgymnasium
Abendsegler
Abendstern
Abendstille
Abendstudium
Abendstunde
Abendtrunk
Dämmerschoppen
Abendunterricht
Abendverkauf
Abendvorstellung
Abendwind
Abendzeit
Abendzeitung
Abenteuer
Abenteuer
Eskapade
Abenteuerdrang
Abenteuerfilm
Abenteurerfilm
Abenteuergeschichte
Abenteurergeschichte
Abenteuerleben
Abenteurerleben
Abenteuerlichkeit
Abenteuerlust
Abenteuerlust
Abenteuerreise
Abenteuerspielplatz
Abenteurer
Abenteurerin
Abenteurergeist
Aber
Aberglaube
Aberglaube
Aberkennung
Entzug
Entziehung
Aberregung
Abessinienkrieg
Abessiv
Abfälligkeit
Abfärben
Abschmieren
Abliegen
Abfackelmast
Abfackelung
Abfackeln
Abfahrauftragssignal
Abfahrtsignal
Abfahrdampfsystem
Abfahrgeschwindigkeit
Abfahrsystem
Abfahrvorgang
Abfahrt
Abflug
Abfahrt
Autobahnabfahrt
Abfahrtsbahnhof
Abfahrtserklärung
Abfahrtsgleis
Abfahrtshocke
Abfahrt-Skistiefel
Abfahrtsignal
Abfahrtslauf
Abfahrtsrennen
Abfahrtsläufer
Abfahrtsläuferin
Abfahrtsort
Abfahrtsplan
Abfahrtsfahrplan
Abfahrtssignal
Abfahrtsignal
Abfahrsignal
Abfahrtstafel
Abfahrtszeit
Abflugszeit
Abflugzeit
Abfall
Müll
Mist
Kehricht
Abfall
Müll
Fertigungsabfall
Straßenabfall
Abfall
Ausschuss
Verschnitt
Abfall
Unrat
Abfall
Abfall
Hausabfall
Kehricht
Abfall
Hausabfall
Abfall
Ausschuss
Abfall
Fallen
Sinken
Abfall
Ansteigen
Abfall
Abtrünnigkeit
Renegatentum
Apostasie
Abfallablagerung
Schuttabladen
Abfallanalyse
Abfallanalytik
Abfallart
Abfallbehörde
Abfallbehandlung
Abfallaufbereitung
Abfallaufbereitungsanlage
Abfallaufkommen
Abfallbeauftragter
Abfallbehälter
Müllbehälter
Abfallbehältnis
Abfallbelastung
Abfallberater
Abfallberaterin
Abfallbeseitigungsfirma
Entsorgungsfachbetrieb
Entsorgungsbetrieb
Entsorgungsfirma
Entsorgungsunternehmen
Abfallbeseitigungsgesetz
Abfallbiomasse
Abfallbunker
Abfallchemikalie
Abfallcontainer
Müllcontainer
Abfalleigenschaft
Abfallen
Gefälle
Abfallendlagerung
Abfaller
Abfalleimer
Mülleimer
Abfallkübel
Mistkübel
Müllkübel
Kehrichteimer
Abfalleimer
Abfallbehälter
Abfalleimer
Abfallentsorgung
Abfallentsorgungsanlage
Müllentsorgungsanlage
Abfallentsorgungsgebühr
Abfallgebühr
Abfallabgabe
Abfallentsorgungsinfrastruktur
Abfallentsorgungspflicht
Abfallentsorgungsverpflichtung
Abfallentsorgungsplan
Abfallentsorgungsplaner
Abfallentsorgungsplanung
Abfallfresser
Abfallgebinde
Abfallgesetz
Abfallgesetzgebung
Abfallgitter
Abfallgrube
Abfallgruppe
Abfallkategorie
Abfallholz
Holzabfall
Abfallkalender
Abfallklasse
Abfallkorb
Abfalllager
Abfalllagerung
Abfallmaterial
Abfallmenge
Müllmenge
Abfallmühle
Abfallprodukt
Abfallprodukt
Abfallerzeugnis
Abprodukt
Abfallraum
Abfallreduzierung
Abfallrohr
Abfallsack
Abfallsammelplatz
Abfallsammelpunkt
Abfallsammelstelle
Abfallsammelsystem
Müllsammelsystem
Sammelsystem
Müllsammlung
Abfallschacht
Abfallschlamm
Abfallseide
Seidenabfall
Abfallsortiereinrichtung
Abfalltechnik
Abfalltechnik
Abfalltransport
Abfallumschlagsstation
Abfallumschlagstelle
Abfalluran
Abfallverdichtungsanlage
Abfallverwertungsanlage
Abfallverwertungsunternehmen
Abfallverwerter
Müllverwertungsunternehmen
Müllverwerter
Abfallverzeichnis
Abfallwiederverwertung
Abfallverwertung
Abfallrecycling
Abproduktverwertung
Abproduktnutzung
Abfallwirtschaft
Abfallbewirtschaftung
Abfallwirtschaftsberatung
Abfallwirtschaftsgesetz
Abfallwirtschaftshof
Altstoffhof
Altstoffsammelstelle
Altstoffzentrum
Recyclinghof
Wertstoffhof
Abfallwirtschaftskonzept
Abfallzeit
Rückfallzeit
Abfallzerkleinerer
Abfallzerkleinerungsmaschine
Abfallzusammensetzung
Abfangeinrichtung
Abfangeinsatz
Abfangen
Abwerfen
Abfangen
Abfangen
Abfangen
Abwerben
Abspenstigmachen
Abfangjagd
Abfangjäger
Abfangklappe
Abfangleitung
Abfangschnellschlussventil
Abfangtau
Abfangventil
Abfangwasser
Abferkelbereich
Abferkelbucht
Abferkeln
Abferkelung
Abferkelstall
Abferkelstand
Kastenstand
Abfederung
Federsystem
Abfertigung
Check-in
Abfertigung
Abfertigungsbüro
Abfertigungsdisziplin
Abfertigungsgesellschaft
Abfertigungsgebühr
Abfertigungshalle
Abfertigungsbereich
Abfertigungsschalter
Abflugschalter
Abfertigungssystem
Abfertigungszone
Abfertigungsstelle
Abfeuerpunkt
Abfeuerungsvorrichtung
Abfindung
Abfindung
Gratifikation
Abfindungssumme
Abfindungsvertrag
Abfindungswert
Abfischung
Abflachschaltung
Abflacher
Abflachung
Abflachung
Abflachung
Abflachungsgebiet
Abflachungsmittel
Abflauen
Abklingen
Nachlassen
Abfließen
Abfluss
Abflugdatum
Abfahrtsdatum
Abflugflughafen
Abflugfreigabe
Abfluggebäude
Abflughafen
Abflughalle
Abflugbereich
Abflugkurs
Abflugpunkt
Abflugraster
Abflugsektor
Abflugsort
Abflugort
Abflugstrecke
Abflugteil
Abflugterminal
Abflugverfahren
Abflugzone
Abfluss
Abfluss
Zwischenabfluss
Oberflächenabfluss
Flächenabfluss
Abfluss
Kapitalabfluss
Warenabfluss
Abfluss
Abflussarmatur
Abflussbecken
Ausguss
Abflussbildung
Abflussdauerkurve
Abflussdauerlinie
Abflussdruck
Abflussfaktor
Abflussfülle
Abflussgitter
Abflussgraben
Abflusshahn
Abflusshindernis
Abflussjahr
Abflusskanal
Abflusskennzahl
Abflussbeiwert
Abflusskoeffizient
Abflussfaktor
Abflussleitung
Ablaufleitung
Abflussloch
Abflussloch
Abflussöffnung
Abfluss
Abflussmengenkurve
Abflusskurve
Abflussmessgerät
Abflussmessnetz
Abflussmessung
Abflussmodell
Abflussöffnung
Abflusssektion
Überfallsektion
Abflussspitze
Spitzenabfluss
Scheitelabfluss
Abflussextrem
Abflussstelle
Abfluss
Abflussregelung
Abflussregime
Abflussregler
Abflussreiniger
Abflussrinne
Rinne
Abflussrohr
Ablaufrohr
Abzugsrohr
Ausflussrohr
Auslassrohr
Ausgussrohr
Abflussleitung
Abflussrohr
Abfluss
Abflusstabelle
Abflusstiefe
Fließtiefe
Abflusstrichter
Abflussverhalten
Abflussvermögen
Durchflussvermögen
Abflusskapazität
Durchflusskapazität
Abflussverringerung
Abflussreduktion
Abflussverzögerung
Abflussvolumen
Abflusssumme
Abflussfracht
Wasserfracht
Abflussvolumen
Abflussfracht
Wasserfracht
Abflussvorhersage
Abflussprognose
Abflusswert
Abflutwasser
Abformen
Abformmasse
Abgussmasse
Abformung
Nachguss
Abformwerkzeug
Abforstung
Abholzung
Abfrage
Abfrage
Abfragebefehl
Abfragebetrieb
Abfragedatum
Abfrageeditor
Abfrageergebnis
Abfragefenster
Abfragefolge
Abfragefrequenz
Abfrageimpuls
Abfrageimpulspaar
Abfragemodus
Abfrageplatz
Abfragestation
Abfrageendgerät
Abfragegerät
Abfragequote
Abfragesystem
Abrufsystem
Online-Abrufsystem
Abfrageverfahren
Abfühler-Stanzer-Freigabe
Abfühlstift
Abführmittel
Laxans
Laxativ
Abführmittel
Abführmittel
Abführung
Abführung
Abführung
Abfüllanlage
Abfüllautomat
Abfüllapparat
Abfüllmaschine
Abfüllbetrieb
Abfüllbetrieb
Abfülldatum
Abfüllen
Abziehen
Abfüllerfirma
Abfüllfirma
Abfüller
Abfüllpumpe
Abfüllstation
Abfülltrichter
Fangtrichter
Abfüllung
Abfüllwaage
Abfuhr
Behebung
Beseitigung
Entfernung
Umzug
Abfuhr
Abfuhr
Korb
Abfuhrsystem
Abfunken
Abgabe
Steuer
Finanzabgabe
Gebühr
Abgabe
Abgabeleistung
Abgabenüberhebung
Abgabenbefreiung
Abgabenbelastung
Abgabenberechnung
Abgabenordnung
Abgabenquote
Abgabepflicht
Abgabenpflicht
Abgabepumpe
Abgabestation
Abgabestelle
Übergabestelle
Anlieferort
Anlieferungsstelle
Abgabetag
Abgang
Abgang
Abgang
Abgang
Schmelzverlust
Abgang
Abgangsabstand
Abgangsbahnhof
Abgangsdatum
Abgangsfehler
Abgangsfehlerwinkel
Abgangsfeld
Abgangsflughafen
Abgangsgruppe
Abgangshafen
Abfahrtshafen
Abgangsklemme
Abgangskontrolle
Abgangskontrolle
Abgangsort
Abgangsstelle
Abgangsprozess
Abgangsrate
Abgangsrichtung
Abgangsstelle
Abgangsursache
Abgangswelle
Abgangswinkel
Abgangszeit
Abgangszeugnis
Abgas
Auspuff
Abgasabführung
Abgasabsaugung
Abgasanalysator
Abgasanalyse
Abgasanlage
Abgasanschluss
Abgasaustrittskanal
Abgasbremse
Abgasdichte
Abgasdruck
Abgasdurchsatz
Abgasemission
Abgasentgiftung
Abgasfahne
Abluftfahne
Abgasfilter
Abgasgegendruck
Abgashaube
Abgaskamin
Abgaskanal
Abgaskatalysator
Katalysator
Kat
Abgaskomponente
Abgaskühler
Abgasleitung
Abgasmenge
Abgasmessstrecke
Abgasmeßstrecke
Abgasnachbehandlung
Abgasniveau
Abgasprobe
Abgasreinigungsanlage
Abgasrohr
Abgasnorm
Abgasrückführung
Abgasrückführung
Abgasrückführungsventil
Abgassammlerhaube
Abgasschalldämpfer
Abluftschalldämpfer
Abgasschlauch
Abgassicherungstemperatur
Abgasstrang
Abgassonderuntersuchung
Abgasströmungssicherung
Abgasstutzen
Abgassystem
Abgastemperatur
Abgastest
Abgastest
Abgasturbine
Abgasturboaufladung
Abgasturbolader
Abgasturboläufer
Abgasuntersuchung
Abgasverlust
Abgasverlust
Abgas-Absauganlage
Abgas-Regelsystem
Abgaswäscher
Rauchgaswäscher
Abgaszähler
Abgeben
Hochtreiben
Abgehen
Abkehr
Abgelegenheit
Einsamkeit
Abgeneigtheit
Abgeordnetenbank
Abgeordnetenhaus
Abgeordnetenkammer
Abgeordnetenkammer
Abgeordnetenmandat
Abgeordnetenversammlung
Abgesang
Abgesang
Abgeschiedenheit
Entlegenheit
Abgeschlossenheit
Abgeschlossenheit
Abgeschlossenheitsrelation
Abgespanntheit
Abgeschlagenheit
Schlappheit
Abglanz
Abgleich
Abgleiten
Gleiten
Gleitung
Abgleichbohle
Abgleichfehler
Abgleichklemme
Abgleichkondensator
Abgleichpunkt
Abgleichregler
Abgleichschalter
Abgleichwiderstand
Abgott
Götze
Abgottschlange
Abgottboa
Königsschlange
Königsboa
Abgötterei
Abgreifen
Abgriff
Abgreifen
Abgrenzer
Begrenzer
Abgrenzung
Begrenzung
Demarkation
Ausscheidung
Begriffsabgrenzung
Abgrenzungsbank
Abgrenzungsdatum
Abgrenzungskonzept
Abgrenzungskonto
Abgrenzungskriterium
Abgrenzungsproblem
Abgrenzungssystem
Abgriff
Abgriff
Anzapfvorrichtung
Abgrund
Schlund
Abgrund
Abgrund
Abguss
Gussform
Abguss
Abhängigkeit
Süchtigkeit
Sucht
Kokainsucht
Sexsucht
Abhänger
Abhängigkeit
Abhängigkeit
Abhängigkeitsgrad
Abhängigkeitsschaltung
Abhängigkeitsverschluss
Abhängigkeitsstruktur
Abhängigkeitssystem
Abhängigkeitsverhältnis
Abhängigkeitsverhältnis
Abhängung
Abhängungsstab
Abhärtung
Gewöhnung
Abhakliste
Abhaldung
Abhaltestrategie
Abhaltung
Traktat
Elaborat
Erguss
Abhang
Abhaspel
Abheben
Abhebe-Formmaschine
Abheben
Abhebesicherung
Absturzsicherung
Abhebezeit
Abhebung
Behebung
Abhebungsgrenze
Abhebungslimit
Behebungsgrenze
Behebungslimit
Abheftbügel
Abheuerungsnachweis
Abmusterungsnachweis
Abhilfe
Gegenmittel
Mittel
Rezept
Remedur
Abhitzekessel
Abhitzeverwertung
Abholadresse
Abholbereich
Abholdatum
Abholgroßhändler
Inhaber
Großmarktinhaber
Abholservice
Abholstelle
Abholtag
Abholtermin
Abholung
Abholen
Abhöraffäre
Abhöranlage
Abhöranlage
Abhörsystem
Abhörskandal
Abholzeit
Abholzen
Abholzung
Abforstung
Rodung
Kahlschlag
Abholzung
Abhorchen
Auskultation
Abhören
Abhören
Abhörgerät
Minispion
Wanze
Abhörgesetz
Abhörkabine
Abhörlautsprecher
Abhörplatz
Abietat
Abietin
Coniferin
Abietinsäure
Sylvinsäure
Abiogenese
Abioseston
Abiozön
Abisolieren
Abisoliergerät
Abisoliermaschine
Abmantelungsgerät
Abisolierlänge
Abisoliermesser
Abisolierwerkzeug
Abisolierzange
Abifeier
Maturafeier
Abiturient
Maturant
Maturand
Abiturient
Maturant
Maturand
Abiturjahrgang
Abijahrgang
Maturajahrgang
Abiturzeitung
Abizeitung
Maturazeitung
Abkantmaschine
Abkantpresse
Abkantung
Abkantung
Abkapselung
Abgeschlossenheit
Abkehr
Abkehr
Abkippen
Abklappern
Reise
Abklatsch
Abklatschpräparat
Abklatschen
Abklatschen
Abklemmen
Abklemmung
Abklettern
Abklingbecken
Abklingbehälter
Abklingcharakteristik
Abklingen
Abklingfaktor
Abklingkonstante
Abklingkurve
Abklingmodul
Abklingwärme
Abklingzeit
Relaxationszeit
Abklingzeitkonstante
Abkochmaschine
Waschmaschine
Abkochung
Absud
Sud
Dekokt
Abkommen
Abkommen
Abkömmlichkeit
Abkömmling
Derivat
Abkoppeln
Ausklinken
Ausrücken
Auslösen
Trennen
Abkühlgeschwindigkeit
Abkühlung
Abkühlung
Kühlung
Abkühlungsart
Abkühlungseffekt
Abkühlungsresistenz
Abkühlungszeit
Abkündigung
Abkürzer
Abkürzsäge
Ablängsäge
Abkürzung
Abkürzung
Abschneider
Abkürzungsdschungel
Buchstabensuppe
Abkürzungsverzeichnis
Abladegebühr
Abladeplatz
Ablass
Ablassöffnung
Ablassleitung
Ablaßleitung
Ablader
Abladestelle
Ablation
Ablatio
Ablation
Ablationsform
Ablationsgradient
Ablationskachel
Ablationsplatte
Ablationskegel
Gruskegel
Ablationssenke
Ablationstal
Ablationstriebwerk
Ablationsvolumen
Ablationswerkstoff
Ablativ
Ablängzange
Ablage
Ablage
Aufstapeln
Aufschichten
Kellern
Ablagefach
Ablagefläche
Ablagekorb
Ablage
Ablagemagazin
Ablageort
Ablageort
Ablageort
Ablageschrank
Ablagestapel
Bogenablage
Ablagesystem
Ablagerung
Ablagerung
Ablagern
Absetzen
Übermurung
Ablagerungsdichte
Ablagerungsmilieu
Ablagerungsfläche
Ablagerungsgeschwindigkeit
Ablagerungsrate
Ablagerungsgebiet
Ablagerungsgestein
Schichtgestein
Sedimentgestein
Sediment
Ablagetisch
Ablagetisch
Ablassbrief
Ablassen
Ablasshahn
Ablasshandel
Ablaßhandel
Ablauf
Ablauf
Ablaufen
Ablauf

In [100]:
def build_dataframe(article_dict):
    df = pd.DataFrame(
        list(article_dict.items()),
        columns=["word", "article"]
    )
    return df

In [101]:
df_art = build_dataframe(art)

In [102]:
df_art.head()

    word article
0      A       n
1    Ais       n
2     As       n
3  Aisis       n
4   Ases       n

In [104]:
art['Katze']

'f'

In [108]:
print(len(art))

158863

In [106]:
df_art.loc['Katze']

KeyError: 'Katze'

In [ ]:
letters = ['a',  'b'	,'c',	'd',	'e',	'f',	'g',	'h'	,   'i',	'j',	'k',	'l',	'm',
              	'n',	'o',	'p',	'q',	'r',	's',	't',	'u',	'v',	'w',
                    	'x',	'y',	'z'	,'ä'	,'ö'	,'ü',	'ß', '0', '-']

In [153]:
def word_prep_rnn(w):
    w = w.lower()
    r = list(w)
    for i in range(len(r)):
        if r[i] not in letters:
            r[i] = '0'
    return r

In [155]:
w = word_prep_rnn('si6gma')
w

['s', 'i', '0', 'g', 'm', 'a']

In [156]:
def onehot(cat):
    n = len(cat)
    oh = []
    for i in range(n):
        vec = [0] * n
        vec[i] = 1
        oh.append(vec)
    oh.append([0]*n)
    return oh

OneHot = onehot(letters)
hot_mapping = dict(zip(letters, OneHot))

In [157]:
def hotX_torch(w):
    r = word_prep_rnn(w)
    HX = [hot_mapping[letter] for letter in r]
    #flatHX = [item for sublist in HX for item in sublist] #flatten the list of lists into a vector
    #return np.array(HX, dtype='int8')
    return torch.tensor(HX)

In [171]:
from torch.nn.utils.rnn import pad_sequence

In [172]:
X = df_art['word'].values
X = pad_sequence([hotX_torch(w) for w in X], batch_first=True)

In [174]:
y = df_art['article'].values

In [175]:
y

<ArrowStringArray>
['n', 'n', 'n', 'n', 'n', 'm', 'm', 'f', 'm', 'm',
 ...
 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n', 'n']
Length: 158863, dtype: str

In [182]:
X[5].shape

torch.Size([56, 32])