In [15]:
import pandas as pd
from src import pipelines as P
from pathlib import Path
import re

In [4]:
nomen = P.get_nomen()

In [5]:
nomen

                   Nomen Artikel
1                    Ich       n
4                    Ist       n
9                     Es       n
11                   Was       m
20                   Wie       n
...                  ...     ...
308571     Teppichmesser       n
308574       Holzspalter       m
308577  Obergesellschaft       f
308582       Brandstelle       f
308591        Bissigkeit       f

[33631 rows x 2 columns]

In [6]:
n2 = pd.read_csv('nouns.csv')

/tmp/ipykernel_48153/3213972919.py:1: DtypeWarning: Columns (0: genus 3, 1: genus 4, 2: nominativ singular*, 3: nominativ singular 3, 4: nominativ singular 4, 5: nominativ plural 3, 6: nominativ plural 4, 7: genitiv singular 3, 8: genitiv singular 4, 9: genitiv plural 3, 10: genitiv plural 4, 11: dativ singular 3, 12: dativ singular 4, 13: dativ plural 3, 14: dativ plural 4, 15: akkusativ singular 3, 16: akkusativ singular 4, 17: akkusativ plural 3, 18: akkusativ plural 4) have mixed types. Specify dtype option on import or set low_memory=False.
  n2 = pd.read_csv('nouns.csv')

In [7]:
n2

,lemma,pos,genus,genus 1,genus 2,genus 3,genus 4,nominativ singular,nominativ singular*,nominativ singular 1,...,akkusativ singular gemischt,akkusativ plural,akkusativ plural*,akkusativ plural 1,akkusativ plural 2,akkusativ plural 3,akkusativ plural 4,akkusativ plural stark,akkusativ plural schwach,akkusativ plural gemischt
0,-algie,"Gebundenes Lexem,Substantiv",f,NaN,NaN,NaN,NaN,-algie,NaN,NaN,...,NaN,-algien,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-ant,"Affix,Substantiv,Suffix",NaN,m,n,NaN,NaN,NaN,NaN,-ant,...,NaN,NaN,NaN,-anten,-ante,NaN,NaN,NaN,NaN,NaN
2,-anz,"Affix,Substantiv,Suffix",f,NaN,NaN,NaN,NaN,-anz,NaN,NaN,...,NaN,-anzen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-chen,"Affix,Substantiv,Suffix",n,NaN,NaN,NaN,NaN,-chen,NaN,NaN,...,NaN,-chen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-elchen,"Affix,Substantiv,Suffix",n,NaN,NaN,NaN,NaN,-elchen,NaN,NaN,...,NaN,-elchen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102439,Ḫāriǧit,Substantiv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102440,’Ndrangheta,Substantiv,f,NaN,NaN,NaN,NaN,’Ndrangheta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102441,’Sgebengu,Substantiv,m,NaN,NaN,NaN,NaN,’Sgebengu,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102442,’s-Gravenhage,"Substantiv,Toponym",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102443,’s-Hertogenbosch,"Substantiv,Toponym",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
def line_read(data):
    article = {
        "Katze": "f"
    }
    with open(data, "r", encoding="utf-8") as file: 
        content = file.read()
        ct = 0
        for line in re.split(r"[\n;]", content):
            line = line.strip()
            words = line.split()
            if(len(words)>1 and len(words[1]) > 2):
                if(words[1][0] == '{' and words[1][2] == '}'):
                    print(words[0])
                    article[words[0]] = words[1][1]
                    ct+=1
                    print(article[words[0]])
            #print(line)
            #ct+=1
    return article

In [60]:
art = line_read('raw_data/de-en.txt')

A
n
Ais
n
As
n
Aisis
n
Ases
n
Aal
m
Aachener
m
Aachenerin
f
Aalbestand
m
Aalspieß
m
Aalen
n
Aalenium
n
Aalfang
m
Aalfischerei
f
Aalhaut
f
Aalleiter
f
Aaltreppe
f
Aalpass
m
Aalräucherei
f
Aalreuse
f
Aalstrich
m
Aalstrich
m
Aalsuppe
f
Aalterrine
f
Aas
n
Aasfleisch
n
Aas
n
Aaronsstab
m
Aasfliege
f
Aasfresser
m
Aasgeier
m
Aasjäger
m
Aaskäfer
m
Aaskrähe
f
Abacá
f
Abaka
f
Manilahanf
m
Abachi
n
Abakusblume
f
Abakussäule
f
A-Batterie
f
A-Betrieb
m
Abazissus
m
Abänderung
f
Modifikation
f
Modifizierung
f
Abänderungsantrag
m
Ergänzungsantrag
m
Zusatzantrag
m
Änderungsantrag
m
Abänderungsbefugnis
f
Abänderungsklage
f
Abänderungsurkunde
f
Abänderungsvorschlag
m
Ergänzungsvorschlag
m
Abandon
m
Abandonerklärung
f
Abandonerklärung
f
Abandonfrist
f
Abandonist
m
Abandonrevers
m
Abarbeitung
f
Abarbeiten
n
Abarbeitungsfolge
f
Abarbeitungszeit
f
Bearbeitungszeit
f
Bearbeitungsdauer
f
Abarbeitungszyklus
m
Abart
f
Variante
f
Variation
f
Abartigkeit
f
Abbau
m
Zersetzung
f
Degradierung
f
Abbau
m
Abbau
m
Abbau
m
Ausbeuten
n
Abbau
m
Abbauen
n
Demontage
f
Zerlegen
n
Abbau
m
Rückbau
m
Abbau
m
Gewinnung
f
Förderung
f
Ausbeutung
f
Abbau
m
Tagebau
m
Abraumbau
m
Abbau
m
Dämpfung
f
Abbaubarkeit
f
Abbaublock
m
Abbauerlaubnis
f
Abbaugenehmigung
f
Abbaufeld
n
Abbaufrist
f
Abbaugebiet
n
Abbaugenehmigungsantrag
m
Abbaugeschwindigkeit
f
Abbaurate
f
Abbaugrad
m
Abbauhammer
m
Pickhammer
m
Abbauhöhe
f
Vorgriff
m
Abbauintoxikation
f
Abbauland
n
Abbauleistung
f
Abbaumaschine
f
Abbauphase
f
Abbaustadium
n
Abbauprodukt
n
Abbauprodukt
n
Abbaureaktion
f
Abbaurevier
n
Abbaurichtung
f
Abbauriss
m
Abbaustoffwechsel
m
Katabolismus
m
Dissimilation
f
Abbauscheibe
f
Abbauschutt
m
Abbaustelle
f
Abbaustoß
m
Stoß
m
Abbaustrecke
f
Abbaustufe
f
Abbauschritt
m
Abbauverfahren
n
Abbauvertrag
m
Abbaukontrakt
m
Abbauvorgang
m
Abbauprozess
m
Abbauwand
f
Abbauwert
m
Abbauwürdigkeit
f
Abbauzeit
f
Abbe
m
Abbé
m
Abbeermaschine
f
Entstielmaschine
f
Abbeilen
n
Abbeizen
n
Abbeizpaste
f
Abbe-Zahl
f
Abbestellung
f
Abbiegen
n
Abbieger
m
Abbiegescheinwerfer
m
Abbiegespur
f
Abbiegestreifen
m
Abbiegeunfall
m
Abbiegeverbot
n
Abbiegeverhalten
n
Abbiegeverkehr
m
Abbiegestelle
f
Abbild
n
Abbildung
f
Zuordnung
f
Ordnungshomomorphismus
m
Abbildungsbreite
f
Klangkörperausdehnung
f
Abbildungsfehler
m
Abbildtheorie
f
Abbildungsgenauigkeit
f
Abbildungsqualität
f
Abbildungsgleichung
f
Abbildungslegende
f
Bildlegende
f
Legende
f
Bildzeile
f
Bildüberschrift
f
Bildunterschrift
f
Abbildungsmaßstab
m
Abbildungsoptik
f
Abbildungsoptik
f
Abbildungsregister
n
Abbildungsverzeichnis
n
Abbindebeginn
m
Abbindebereich
m
Abbindeende
n
Abbindebehandlung
f
Abbindebeschleuniger
m
Abbindebeschleunigung
f
Abbindedauer
f
Abbindeenergie
f
Abbinden
n
Unterbinden
n
Unterbindung
f
Ligatur
f
Abbinden
n
Abbindeplatz
m
Abbindelager
n
Abbindeprozess
m
Abbindevorgang
m
Abbindeverlauf
m
Abbindeprüfung
f
Abbindereaktion
f
Abbinderegulator
m
Abbindeschwindung
f
Abbindeschwund
m
Abbindesteuerung
f
Abbindestörung
f
Abbindetemperatur
f
Abbindetest
m
Abbindeprüfung
f
Abbindeverhalten
n
Abbindeverzögerer
m
Abbindewasser
n
Abbindewärme
f
Hydratationswärme
f
Abbindewärme
f
Abbindezeit
f
Abbindezeit
f
Abbindungsfaden
m
Unterbindungsfaden
m
Ligaturfaden
m
Abbitte
f
Abblaseabsperrventil
n
Abblasebehälter
m
Abblasetank
m
Abblasebehälterkühler
m
Abblasedampf
m
Abblasedruck
m
Abblasedruckregler
m
Abblaseeinrichtung
f
Abblaseeinrichtung
f
Abblasegrenzdruckregler
m
Abblasehaube
f
Abblaseleistung
f
Abblaseleitung
f
Abblasemast
m
Abblasemenge
f
Abblaseregelung
f
Abblaseregelventil
n
Abblaserohr
n
Ausblaserohr
n
Durchblaserohr
n
Abblaseschalldämpfer
m
Abblaseschieber
m
Abblaseventil
n
Abblaseschnellschlussventil
n
Abblaseschnellschlußventil
n
Abblaseschubventil
n
Abblasestation
f
Abblasesteuerung
f
Abblasetauchspulregler
m
Abblaseventil
n
Umluftventil
n
Abblaseverhältnisdruckregler
m
Abblasevorrichtung
f
Abblättern
n
Abplatzen
n
Abschiefern
n
Abschieferung
f
Abschilfern
n
Abschuppung
f
Abblättern
n
Abblätterung
f
Abblättern
n
Absplitterung
f
Absplittern
n
Abblende
f
Ausblende
f
Abblenden
n
Abblenden
n
Abblendlicht
n
Abblendrelais
n
Abblendschalter
m
Abblendung
f
Abbolzung
f
Abbrand
m
Abbrand
m
Abbrand
m
Atomabbrand
m
Abbrandberechnung
f
Abbrechen
n
Aufbrechen
n
Aufbruch
m
Abbrechen
n
Abbrecher
m
Abbrecherin
f
Abbrechung
f
Abbremsplatz
m
Abbrechversuch
m
Abbremsstelle
f
Abbremsung
f
Verzögerung
f
Abbremsvorgang
m
Abbremszeit
f
Abbremszeit
f
Abbrenneinrichtung
f
Abbrennen
n
Abbrennrate
f
Abbrenntemperatur
f
Abbrennzeit
f
Abbrennzeit
f
Abbrennstumpfschweißen
n
Abbringen
n
Abhalten
n
Abbröckeln
n
Abblättern
n
Abplatzen
n
Absplittern
n
Abbröckelung
f
Abbruch
m
Abbrechen
n
Abbruch
m
Abriss
m
Schleifen
n
Abbruch
m
Abbruch
m
Abbruch
m
Abbruch
m
Abbruch
m
Abschneiden
n
Trunkierung
f
Abbruch
m
Abbruchabfall
m
Abbruchanforderungssignal
n
Abbruchantrag
m
Abbrucharbeiter
m
Abbruchbedingung
f
Abbruchbagger
m
Abbruchbeton
m
Abbruchblutung
f
Entzugsblutung
f
Abbruchcode
m
Abbruchfehler
m
Abbrechfehler
m
Abbruchfirma
f
Abbruchunternehmen
n
Abbruchgebot
n
Abbruchanordnung
f
Abbruchanweisung
f
Abbruchorder
f
Abbruchgenehmigung
f
Abbruchhammer
m
Abbruchgrundstück
n
Abbruchhaus
n
Abbruchholz
n
Abbruchkante
f
Bruchkante
f
Abrisskante
f
Abbruchkolonne
f
Sprengkommando
n
Sprengtrupp
m
Abbruchkostenschätzung
f
Abbruchkriterium
n
Abbruchmakro
n
Abbruchmaterial
n
Abbruchmethode
f
Abbruchphase
f
Abbruchplan
m
Abbruchplaner
m
Abbruchplanung
f
Abbruchpreis
m
Abbruchprojekt
n
Abbruchprozess
m
Abbruchvorgang
m
Abbruchreaktion
f
Abbruchschaufel
f
Abbruchlöffel
m
Abbruchschere
f
Abbruchschutt
m
Abbruchsimulation
f
Abbruchspezialist
m
Abbruchstelle
f
Abbruchtechniker
m
Abbruchufer
f
Abbruchüberwachung
f
Abbruchverfahren
n
Abbruchverzögerung
f
Abbruchaufschub
m
Abbruchvorbereitung
f
Abbruchwerkzeug
n
Abbruchzone
f
Betrug
m
Abbuchung
f
Belastung
f
Abbuchungsauftrag
m
Abbuchungszeitraum
m
ABC-Abwehr
f
ABC-Profil
n
Abc-Schütze
m
I-Dotz
m
I-Dötzchen
n
I-Männchen
n
Taferlklassler
m
Tafelkratzer
m
ABC-Spürpanzer
m
ABC-Terrorismus
m
Superterrorismus
m
Abdachung
f
Schräge
f
Böschung
f
Abdampf
m
Abdampfdruck
m
Abdampfdurchsatz
m
Abdampfende
n
Abdampfenergie
f
Abdampffeuchte
f
Abdampfflansch
m
Abdampfflut
f
Abdampfgehäuse
n
Abdampfhaube
f
Abdampfkrümmer
m
Abdampfleitung
f
Abdampfmenge
f
Abdampfnässe
f
Abdampfquerschnitt
m
Abdampfrückstand
m
Abdampfringraum
m
Abdampfspeicher
m
Abdampfstutzen
m
Abdampfteil
n
Abdampftemperatur
f
Abdampfturbine
f
Abdampfverbindung
f
Abdampfvolumen
n
Abdampfvorwärmer
m
Abdampfverlust
m
Abdankung
f
Zurücktreten
n
Abdankung
f
Abdeckband
m
Abdecker
m
Schinder
m
Kadaverbeseitiger
m
Abdeckerei
f
Abdeckfolie
f
Abdeckhaube
f
Abdeckkappe
f
Kappe
f
Abdeckklappe
f
Abdeckklebeband
n
Abdeckband
n
Abklebeband
n
Abklebband
n
Abdecklack
m
Abdeckmaterial
n
Abdeckpapier
n
Abdeckmutter
f
Abdeckplane
f
Abdeckplatte
f
Abdeckplatte
f
Abdeckstein
m
Abdeckplatte
f
Abdeckprofil
n
Abdeckrahmen
m
Abdeckring
m
Abdeckscheibe
f
Abdeckschraube
f
Abdeckstift
m
Abdeckung
f
Abdeckung
f
Abdeckziegel
m
Abdeckung
f
Abdeckung
f
Bedeckung
f
Verhüllung
f
Abdeckung
f
Abdeckung
f
Freilegung
f
Rückwand
f
Abdichten
n
Abdichtung
f
Abdichtblech
n
Abdichtbürste
f
Abdichten
n
Abdichten
n
Bauwerksabdichtung
f
Abdichten
n
Abdichtung
f
Abdichter
m
Abdichtfarbe
f
Abdichtgummi
m
Dichtgummi
m
Dichtungsgummi
m
Abdichthülse
f
Abdichtmasse
f
Abdichtungsmasse
f
Abdichtrahmen
m
Abdichtring
m
Abdichtstreifen
n
Dichtungsleiste
f
Abdichttopf
m
Abdichtungsband
n
Abdichtungsfolie
f
Abdichtungsleiste
f
Abdichtleiste
f
Abdichtungsmaterial
n
Abdichtungsmethode
f
Abdichtmethode
f
Abdichtungsverfahren
n
Abdichtverfahren
n
Abdichtungspaste
f
Abdichtungspfropfen
m
Abdichtungsreserve
f
Abdichtungssystem
n
Abdichtungsvorrichtung
f
Abdichtwand
f
Abdominallavage
f
Abdominalsegment
n
Abdrängungsschreiber
m
Abdriftschreiber
m
Abdreheisen
n
Abdrehen
n
Abdruck
m
Abdruck
m
Guss
m
Abguss
m
Abdruck
m
Eindruck
m
Gepräge
n
Abdruck
m
Prägung
f
Abdruckmasse
f
Abdrückdeckel
m
Abdrückmutter
f
Abdrückpumpe
f
Abdrückschraube
f
Abdrücksignal
n
Abdrückvorrichtung
f
Abdunkelungsvorrichtung
f
Abduktion
f
Abduktionslähmung
f
Abduktivismus
m
Abduktor
m
Abdunklung
f
Abdunklungsvorhang
m
Verdunklungsvorhang
m
Verdunkelungsvorhang
m
Abdunklung
f
Verdunklung
f
Abelit
m
Abelson-Tukey-Score-Test
m
Abend
m
Abend
m
Abendandacht
f
Abendandacht
f
Abendgottesdienst
m
Abendanzug
m
Abendarbeit
f
Abendausgabe
f
Abendblatt
n
Abendbrotzeit
f
Abendessenzeit
f
Abenddämmerung
f
Dämmerung
f
Dämmer
m
Abenddämmerung
f
Niedergang
m
Ausklang
m
Abendessen
n
Abendbrot
n
Nachtmahl
n
Nachtessen
n
Znacht
n
Gute-Nacht-Imbiss
m
Abendessen
n
Abendgebet
n
Abendgesellschaft
f
Abendglocke
f
Abendgottesdienst
m
Abendhimmel
m
Abendkarte
f
Abendkasse
f
Kasse
f
Abendkassa
f
Kassa
f
Abendkleid
n
Abendkleid
n
Abendgarderobe
f
Abendrobe
f
Abendkleidung
f
Abendkurs
m
Abendland
n
Okzident
m
Westen
m
Abendmahl
n
Altarssakrament
n
Eucharistie
f
Abendlicht
n
Abendluft
f
Abendmahlsgottesdienst
m
Abendmahlswein
m
Abendmahlzeit
f
Abendmesse
f
Abendgottesdienst
m
Abendmode
f
Abendpfauenauge
n
Abendpost
f
Abendprogramm
n
Abendrot
n
Abendröte
f
Abendröte
f
Abendschule
f
Abendgymnasium
n
Abendsegler
m
Abendstern
m
Abendstille
f
Abendstudium
n
Abendstunde
f
Abendtrunk
m
Dämmerschoppen
m
Abendunterricht
m
Abendverkauf
m
Abendvorstellung
f
Abendwind
m
Abendzeit
f
Abendzeitung
f
Abenteuer
n
Abenteuer
n
Eskapade
f
Abenteuerdrang
m
Abenteuerfilm
m
Abenteurerfilm
m
Abenteuergeschichte
f
Abenteurergeschichte
f
Abenteuerleben
n
Abenteurerleben
n
Abenteuerlichkeit
f
Abenteuerlust
f
Abenteuerlust
f
Abenteuerreise
f
Abenteuerspielplatz
m
Abenteurer
m
Abenteurerin
f
Abenteurergeist
m
Aber
n
Aberglaube
m
Aberglaube
m
Aberkennung
f
Entzug
m
Entziehung
f
Aberregung
f
Abessinienkrieg
m
Abessiv
m
Abfälligkeit
f
Abfärben
n
Abschmieren
n
Abliegen
n
Abfackelmast
m
Abfackelung
f
Abfackeln
n
Abfahrauftragssignal
n
Abfahrtsignal
n
Abfahrdampfsystem
n
Abfahrgeschwindigkeit
f
Abfahrsystem
n
Abfahrvorgang
m
Abfahrt
f
Abflug
m
Abfahrt
f
Autobahnabfahrt
f
Abfahrtsbahnhof
m
Abfahrtserklärung
f
Abfahrtsgleis
n
Abfahrtshocke
f
Abfahrt-Skistiefel
m
Abfahrtsignal
n
Abfahrtslauf
m
Abfahrtsrennen
n
Abfahrtsläufer
m
Abfahrtsläuferin
f
Abfahrtsort
m
Abfahrtsplan
m
Abfahrtsfahrplan
m
Abfahrtssignal
n
Abfahrtsignal
n
Abfahrsignal
n
Abfahrtstafel
f
Abfahrtszeit
f
Abflugszeit
f
Abflugzeit
f
Abfall
m
Müll
m
Mist
m
Kehricht
m
Abfall
m
Müll
m
Fertigungsabfall
m
Straßenabfall
m
Abfall
m
Ausschuss
m
Verschnitt
m
Abfall
m
Unrat
m
Abfall
m
Abfall
m
Hausabfall
m
Kehricht
m
Abfall
m
Hausabfall
m
Abfall
m
Ausschuss
m
Abfall
m
Fallen
n
Sinken
n
Abfall
m
Ansteigen
n
Abfall
m
Abtrünnigkeit
f
Renegatentum
n
Apostasie
f
Abfallablagerung
f
Schuttabladen
n
Abfallanalyse
f
Abfallanalytik
f
Abfallart
f
Abfallbehörde
f
Abfallbehandlung
f
Abfallaufbereitung
f
Abfallaufbereitungsanlage
f
Abfallaufkommen
n
Abfallbeauftragter
m
Abfallbehälter
m
Müllbehälter
m
Abfallbehältnis
n
Abfallbelastung
f
Abfallberater
m
Abfallberaterin
f
Abfallbeseitigungsfirma
f
Entsorgungsfachbetrieb
m
Entsorgungsbetrieb
m
Entsorgungsfirma
f
Entsorgungsunternehmen
n
Abfallbeseitigungsgesetz
n
Abfallbiomasse
f
Abfallbunker
m
Abfallchemikalie
f
Abfallcontainer
f
Müllcontainer
f
Abfalleigenschaft
f
Abfallen
n
Gefälle
n
Abfallendlagerung
f
Abfaller
m
Abfalleimer
m
Mülleimer
m
Abfallkübel
m
Mistkübel
m
Müllkübel
m
Kehrichteimer
m
Abfalleimer
m
Abfallbehälter
m
Abfalleimer
m
Abfallentsorgung
f
Abfallentsorgungsanlage
f
Müllentsorgungsanlage
f
Abfallentsorgungsgebühr
f
Abfallgebühr
f
Abfallabgabe
f
Abfallentsorgungsinfrastruktur
f
Abfallentsorgungspflicht
f
Abfallentsorgungsverpflichtung
f
Abfallentsorgungsplan
m
Abfallentsorgungsplaner
m
Abfallentsorgungsplanung
f
Abfallfresser
m
Abfallgebinde
n
Abfallgesetz
n
Abfallgesetzgebung
f
Abfallgitter
n
Abfallgrube
f
Abfallgruppe
f
Abfallkategorie
f
Abfallholz
n
Holzabfall
m
Abfallkalender
m
Abfallklasse
f
Abfallkorb
m
Abfalllager
n
Abfalllagerung
f
Abfallmaterial
n
Abfallmenge
f
Müllmenge
f
Abfallmühle
f
Abfallprodukt
n
Abfallprodukt
n
Abfallerzeugnis
n
Abprodukt
n
Abfallraum
m
Abfallreduzierung
f
Abfallrohr
n
Abfallsack
m
Abfallsammelplatz
m
Abfallsammelpunkt
m
Abfallsammelstelle
f
Abfallsammelsystem
n
Müllsammelsystem
n
Sammelsystem
n
Müllsammlung
f
Abfallschacht
m
Abfallschlamm
m
Abfallseide
f
Seidenabfall
m
Abfallsortiereinrichtung
f
Abfalltechnik
f
Abfalltechnik
f
Abfalltransport
m
Abfallumschlagsstation
f
Abfallumschlagstelle
f
Abfalluran
n
Abfallverdichtungsanlage
f
Abfallverwertungsanlage
f
Abfallverwertungsunternehmen
n
Abfallverwerter
m
Müllverwertungsunternehmen
n
Müllverwerter
m
Abfallverzeichnis
n
Abfallwiederverwertung
f
Abfallverwertung
f
Abfallrecycling
n
Abproduktverwertung
f
Abproduktnutzung
f
Abfallwirtschaft
f
Abfallbewirtschaftung
f
Abfallwirtschaftsberatung
f
Abfallwirtschaftsgesetz
n
Abfallwirtschaftshof
m
Altstoffhof
m
Altstoffsammelstelle
f
Altstoffzentrum
n
Recyclinghof
m
Wertstoffhof
m
Abfallwirtschaftskonzept
n
Abfallzeit
f
Rückfallzeit
f
Abfallzerkleinerer
m
Abfallzerkleinerungsmaschine
f
Abfallzusammensetzung
f
Abfangeinrichtung
f
Abfangeinsatz
m
Abfangen
n
Abwerfen
n
Abfangen
n
Abfangen
n
Abfangen
n
Abwerben
n
Abspenstigmachen
n
Abfangjagd
f
Abfangjäger
m
Abfangklappe
f
Abfangleitung
f
Abfangschnellschlussventil
n
Abfangtau
n
Abfangventil
f
Abfangwasser
n
Abferkelbereich
f
Abferkelbucht
f
Abferkeln
n
Abferkelung
f
Abferkelstall
m
Abferkelstand
m
Kastenstand
m
Abfederung
f
Federsystem
n
Abfertigung
f
Check-in
n
Abfertigung
f
Abfertigungsbüro
n
Abfertigungsdisziplin
f
Abfertigungsgesellschaft
f
Abfertigungsgebühr
f
Abfertigungshalle
f
Abfertigungsbereich
m
Abfertigungsschalter
m
Abflugschalter
m
Abfertigungssystem
n
Abfertigungszone
f
Abfertigungsstelle
f
Abfeuerpunkt
m
Abfeuerungsvorrichtung
f
Abfindung
f
Abfindung
f
Gratifikation
f
Abfindungssumme
f
Abfindungsvertrag
m
Abfindungswert
m
Abfischung
f
Abflachschaltung
f
Abflacher
m
Abflachung
f
Abflachung
f
Abflachung
f
Abflachungsgebiet
n
Abflachungsmittel
n
Abflauen
n
Abklingen
n
Nachlassen
n
Abfließen
n
Abfluss
m
Abflugdatum
n
Abfahrtsdatum
n
Abflugflughafen
m
Abflugfreigabe
f
Abfluggebäude
n
Abflughafen
m
Abflughalle
f
Abflugbereich
m
Abflugkurs
m
Abflugpunkt
m
Abflugraster
n
Abflugsektor
m
Abflugsort
m
Abflugort
m
Abflugstrecke
f
Abflugteil
m
Abflugterminal
n
Abflugverfahren
n
Abflugzone
f
Abfluss
m
Abfluss
m
Zwischenabfluss
m
Oberflächenabfluss
m
Flächenabfluss
m
Abfluss
m
Kapitalabfluss
m
Warenabfluss
m
Abfluss
m
Abflussarmatur
f
Abflussbecken
n
Ausguss
m
Abflussbildung
f
Abflussdauerkurve
f
Abflussdauerlinie
f
Abflussdruck
m
Abflussfaktor
m
Abflussfülle
f
Abflussgitter
n
Abflussgraben
m
Abflusshahn
m
Abflusshindernis
n
Abflussjahr
n
Abflusskanal
m
Abflusskennzahl
f
Abflussbeiwert
m
Abflusskoeffizient
m
Abflussfaktor
m
Abflussleitung
f
Ablaufleitung
f
Abflussloch
n
Abflussloch
n
Abflussöffnung
f
Abfluss
m
Abflussmengenkurve
f
Abflusskurve
f
Abflussmessgerät
n
Abflussmessnetz
n
Abflussmessung
f
Abflussmodell
n
Abflussöffnung
f
Abflusssektion
f
Überfallsektion
f
Abflussspitze
f
Spitzenabfluss
m
Scheitelabfluss
m
Abflussextrem
n
Abflussstelle
f
Abfluss
m
Abflussregelung
f
Abflussregime
n
Abflussregler
m
Abflussreiniger
m
Abflussrinne
f
Rinne
f
Abflussrohr
n
Ablaufrohr
n
Abzugsrohr
n
Ausflussrohr
n
Auslassrohr
n
Ausgussrohr
n
Abflussleitung
f
Abflussrohr
n
Abfluss
m
Abflusstabelle
f
Abflusstiefe
f
Fließtiefe
f
Abflusstrichter
m
Abflussverhalten
n
Abflussvermögen
n
Durchflussvermögen
n
Abflusskapazität
f
Durchflusskapazität
f
Abflussverringerung
f
Abflussreduktion
f
Abflussverzögerung
f
Abflussvolumen
n
Abflusssumme
f
Abflussfracht
f
Wasserfracht
f
Abflussvolumen
n
Abflussfracht
f
Wasserfracht
f
Abflussvorhersage
f
Abflussprognose
f
Abflusswert
m
Abflutwasser
n
Abformen
n
Abformmasse
f
Abgussmasse
f
Abformung
f
Nachguss
m
Abformwerkzeug
n
Abforstung
f
Abholzung
f
Abfrage
f
Abfrage
f
Abfragebefehl
m
Abfragebetrieb
m
Abfragedatum
n
Abfrageeditor
m
Abfrageergebnis
n
Abfragefenster
n
Abfragefolge
f
Abfragefrequenz
f
Abfrageimpuls
m
Abfrageimpulspaar
n
Abfragemodus
m
Abfrageplatz
m
Abfragestation
f
Abfrageendgerät
n
Abfragegerät
n
Abfragequote
f
Abfragesystem
n
Abrufsystem
n
Online-Abrufsystem
n
Abfrageverfahren
n
Abfühler-Stanzer-Freigabe
f
Abfühlstift
m
Abführmittel
n
Laxans
n
Laxativ
n
Abführmittel
n
Abführmittel
n
Abführung
f
Abführung
f
Abführung
f
Abfüllanlage
f
Abfüllautomat
m
Abfüllapparat
m
Abfüllmaschine
f
Abfüllbetrieb
m
Abfüllbetrieb
m
Abfülldatum
n
Abfüllen
n
Abziehen
n
Abfüllerfirma
f
Abfüllfirma
f
Abfüller
m
Abfüllpumpe
f
Abfüllstation
f
Abfülltrichter
m
Fangtrichter
m
Abfüllung
f
Abfüllwaage
f
Abfuhr
f
Behebung
f
Beseitigung
f
Entfernung
f
Umzug
m
Abfuhr
f
Abfuhr
f
Korb
m
Abfuhrsystem
n
Abfunken
n
Abgabe
f
Steuer
f
Finanzabgabe
f
Gebühr
f
Abgabe
f
Abgabeleistung
f
Abgabenüberhebung
f
Abgabenbefreiung
f
Abgabenbelastung
f
Abgabenberechnung
f
Abgabenordnung
f
Abgabenquote
f
Abgabepflicht
f
Abgabenpflicht
f
Abgabepumpe
f
Abgabestation
f
Abgabestelle
f
Übergabestelle
f
Anlieferort
m
Anlieferungsstelle
f
Abgabetag
m
Abgang
m
Abgang
m
Abgang
m
Abgang
m
Schmelzverlust
m
Abgang
m
Abgangsabstand
m
Abgangsbahnhof
m
Abgangsdatum
n
Abgangsfehler
m
Abgangsfehlerwinkel
m
Abgangsfeld
n
Abgangsflughafen
m
Abgangsgruppe
f
Abgangshafen
m
Abfahrtshafen
m
Abgangsklemme
f
Abgangskontrolle
f
Abgangskontrolle
f
Abgangsort
m
Abgangsstelle
f
Abgangsprozess
m
Abgangsrate
f
Abgangsrichtung
f
Abgangsstelle
f
Abgangsursache
f
Abgangswelle
f
Abgangswinkel
m
Abgangszeit
f
Abgangszeugnis
n
Abgas
n
Auspuff
m
Abgasabführung
f
Abgasabsaugung
f
Abgasanalysator
m
Abgasanalyse
f
Abgasanlage
f
Abgasanschluss
m
Abgasaustrittskanal
m
Abgasbremse
f
Abgasdichte
f
Abgasdruck
m
Abgasdurchsatz
m
Abgasemission
f
Abgasentgiftung
f
Abgasfahne
f
Abluftfahne
f
Abgasfilter
m
Abgasgegendruck
m
Abgashaube
f
Abgaskamin
m
Abgaskanal
m
Abgaskatalysator
m
Katalysator
m
Kat
m
Abgaskomponente
f
Abgaskühler
m
Abgasleitung
f
Abgasmenge
f
Abgasmessstrecke
f
Abgasmeßstrecke
f
Abgasnachbehandlung
f
Abgasniveau
n
Abgasprobe
f
Abgasreinigungsanlage
f
Abgasrohr
n
Abgasnorm
f
Abgasrückführung
f
Abgasrückführung
f
Abgasrückführungsventil
n
Abgassammlerhaube
f
Abgasschalldämpfer
m
Abluftschalldämpfer
m
Abgasschlauch
m
Abgassicherungstemperatur
f
Abgasstrang
m
Abgassonderuntersuchung
f
Abgasströmungssicherung
f
Abgasstutzen
m
Abgassystem
n
Abgastemperatur
f
Abgastest
m
Abgastest
m
Abgasturbine
f
Abgasturboaufladung
f
Abgasturbolader
m
Abgasturboläufer
m
Abgasuntersuchung
f
Abgasverlust
m
Abgasverlust
m
Abgas-Absauganlage
f
Abgas-Regelsystem
n
Abgaswäscher
m
Rauchgaswäscher
m
Abgaszähler
m
Abgeben
n
Hochtreiben
n
Abgehen
n
Abkehr
f
Abgelegenheit
f
Einsamkeit
f
Abgeneigtheit
f
Abgeordnetenbank
f
Abgeordnetenhaus
n
Abgeordnetenkammer
f
Abgeordnetenkammer
f
Abgeordnetenmandat
n
Abgeordnetenversammlung
f
Abgesang
m
Abgesang
m
Abgeschiedenheit
f
Entlegenheit
f
Abgeschlossenheit
f
Abgeschlossenheit
f
Abgeschlossenheitsrelation
f
Abgespanntheit
f
Abgeschlagenheit
f
Schlappheit
f
Abglanz
m
Abgleich
m
Abgleiten
n
Gleiten
n
Gleitung
f
Abgleichbohle
f
Abgleichfehler
m
Abgleichklemme
f
Abgleichkondensator
m
Abgleichpunkt
m
Abgleichregler
m
Abgleichschalter
m
Abgleichwiderstand
m
Abgott
m
Götze
m
Abgottschlange
f
Abgottboa
f
Königsschlange
f
Königsboa
f
Abgötterei
f
Abgreifen
n
Abgriff
m
Abgreifen
n
Abgrenzer
m
Begrenzer
m
Abgrenzung
f
Begrenzung
f
Demarkation
f
Ausscheidung
f
Begriffsabgrenzung
f
Abgrenzungsbank
f
Abgrenzungsdatum
n
Abgrenzungskonzept
n
Abgrenzungskonto
n
Abgrenzungskriterium
n
Abgrenzungsproblem
n
Abgrenzungssystem
n
Abgriff
m
Abgriff
m
Anzapfvorrichtung
f
Abgrund
m
Schlund
m
Abgrund
m
Abgrund
m
Abguss
m
Gussform
f
Abguss
m
Abhängigkeit
f
Süchtigkeit
f
Sucht
f
Kokainsucht
f
Sexsucht
f
Abhänger
m
Abhängigkeit
f
Abhängigkeit
f
Abhängigkeitsgrad
m
Abhängigkeitsschaltung
f
Abhängigkeitsverschluss
m
Abhängigkeitsstruktur
f
Abhängigkeitssystem
n
Abhängigkeitsverhältnis
n
Abhängigkeitsverhältnis
n
Abhängung
f
Abhängungsstab
m
Abhärtung
f
Gewöhnung
f
Abhakliste
f
Abhaldung
f
Abhaltestrategie
f
Abhaltung
f
Traktat
n
Elaborat
n
Erguss
m
Abhang
m
Abhaspel
f
Abheben
n
Abhebe-Formmaschine
f
Abheben
n
Abhebesicherung
f
Absturzsicherung
f
Abhebezeit
f

In [66]:
def build_dataframe(article_dict):
    df = pd.DataFrame(
        list(article_dict.items()),
        columns=["word", "article"]
    )
    return df

In [68]:
df_art = build_dataframe(art)

In [69]:
df_art.head()

    word article
0  Katze       f
1      A       n
2    Ais       n
3     As       n
4  Aisis       n

In [65]:
art['Hund']

'm'